# Generated by Django 5.0.4 on 2024-05-06 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('brands_pic', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('cat_pic', models.ImageField(null=True, upload_to='image')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=250)),
                ('main_pic', models.ImageField(null=True, upload_to='image')),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('price_with_sale', models.IntegerField(blank=True)),
                ('articul', models.CharField(blank=True, max_length=50)),
                ('sale_confirmed', models.BooleanField()),
                ('brand_id', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='api_app.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.category')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.colors')),
            ],
        ),
        migrations.CreateModel(
            name='GoodToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.goods')),
            ],
        ),
        migrations.CreateModel(
            name='HugeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.goods')),
            ],
        ),
        migrations.CreateModel(
            name='MainBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.brands')),
            ],
        ),
        migrations.CreateModel(
            name='MainCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='MainProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('goods', models.ManyToManyField(through='api_app.GoodToUser', to='api_app.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='goodtouser',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.order'),
        ),
        migrations.CreateModel(
            name='SizesToGoodTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.goods')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.sizes')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='size',
            field=models.ManyToManyField(through='api_app.SizesToGoodTable', to='api_app.sizes'),
        ),
    ]
